
/* Este modelo de domínio deve respeitar DDD */
@startuml
'skinparam linetype ortho
'left to right direction

class Organizacao{}

'class Colaborador{
 '-int numMecanografico
 '-String nome
 '-String nomeCompleto
 '-Date dataNascimento
 '-int contacto
'}

class Equipa {
 -int id
 -String acronimo
 -String nomeEquipa
}

class TipoEquipa{
 -int id
 -String descricao
 -String cor
}

class CriterioAcesso{}

class CatalogoServico{
 -int id
 -String titulo
 -String descBreve
 -String descCompleta
 -String icone
}

class Servico{
 -int id
 -String descBreve
 -String descCompleta
 -String palavrasChave
}


class NiveisCriticidade{
 -int nivel
}

class Urgencia {
 -int nivelUrgencia
}

class Prioridade{
 -int nivelPrioridade
}

class Tarefa{}

class TarefaManual{}

class TarefaAutomatica{}

class Script{}

class Formulario{
 -int idServico
 }

class Pedido{}

class Feedback{}

class AtividadeAprovacao{}

Organizacao "1" -- "1..*" Equipa

Equipa "1" -- "1" TipoEquipa
Equipa "*" -- "0..1" CriterioAcesso
CriterioAcesso "*" -- "1" CatalogoServico

CatalogoServico "1" -- "1..*" Servico
Servico "*" -- "1" NiveisCriticidade
Pedido "*" -- "1" Urgencia
Pedido "*" -- "1" Prioridade
Servico "1" -- "*" Formulario
TarefaAutomatica "1" -- "1" Script

TarefaAutomatica -> Tarefa
TarefaManual -> Tarefa

Pedido "1" -- "1" Formulario
Pedido "*" -- "1" Servico
Pedido "1" -- "1" Feedback
Pedido "1" -- "1" AtividadeAprovacao

Pedido "1" --- "1" Tarefa

AtividadeAprovacao "1" -- "1" Tarefa
TarefaManual "1" -- "1" Formulario




@enduml