
/* Este modelo de domínio deve respeitar DDD */
@startuml

skinparam linetype ortho

namespace Agregado_Equipa #DAAAAA{

entity Equipa {
 -int id
 -String acronimo
 -String nomeEquipa
}

class EquipaId <<Value Object>>{}
class Cor <<Value Object>>{}
class Descricao <<Value Object>>{}

.Equipa "1" --> "1"  Cor
.Equipa "1" --> "1" EquipaId
.Equipa "1" --> "1" Descricao
}


namespace Agregado_TipoEquipa #BAADDC{
entity TipoEquipa{
 -int id
 -String descricao
 -String cor
}
class TipoEquipaId <<Value Object>>{}
class Cor <<Value Object>>{}

.TipoEquipa --> TipoEquipaId
.TipoEquipa --> Cor
.TipoEquipa --> Agregado_Equipa.Descricao
}


namespace Agregado_Colaborador #DEEFFA {
entity Colaborador{
}

class NomeCompleto <<Value Object>>{
 -String PrimeiroNome
 -String[] NomesMeio
 -String UltimoNome
 }

class NomeAbreviado <<Value Object>>{
 -String PrimeiroNome
 -String UltimoNome
}

class Morada <<Value Object>>{
 -Cidade cidade
 -String rua
 -CodigoPostal codigoPostal
}

class Data <<Value Object>>{
 -int dia
 -int mes
 -int ano
}

class NumeroMecanografico <<Value Object>>{}
class Contacto <<Value Object>>{}
Class Funcao <<Value Object>>{}
Class CodigoEquipa <<Value Object>>{}

    .Equipa "1" -- "1..*" .Colaborador : "Composta por >"
    .Colaborador "1" --> "1" NomeCompleto
    .Colaborador "1" --> "1" NomeAbreviado
    .Colaborador "1" --> "1" Morada
    .Colaborador "1" --> "1" Data
    .Colaborador "1" --> "1" NumeroMecanografico
    .Colaborador "1" --> "1" Contacto
    .Colaborador "1" --> "1" Funcao
    .Colaborador "1" --> "1" CodigoEquipa
}

namespace Agregado_Utilizador #BBEFFA {
entity Utilizador {

 }

class NomeUtilizador{}
class Password{}
class Email{}
class Papel
    .Utilizador "1" --> "1" NomeUtilizador
    .Utilizador "1" --> "1" Password
    .Utilizador "1" --> "1" Email
    .Utilizador "1" --> "1" Papel
    .Colaborador "1" -|> "1" .Utilizador : "É um >"

}
entity Organizacao{
 -Nome nome
 -String descricao
}


class Revisao{
 -int avaliacao
 -String observacao
}

Organizacao "1" ..> "1..*" .Equipa : define >
Organizacao "1" ..> "1..*" .TipoEquipa : define >
Organizacao "1" ..> "1..*" .Colaborador
Organizacao "1" ..> "1..*" .Utilizador

Revisao "*" -- "1" Colaborador
Revisao "1" --> "1" Agregado_Colaborador.Data
.Equipa "1" --> "1" .TipoEquipa : pertence >
@enduml