
/* Este modelo de domínio deve respeitar DDD */
@startuml
skinparam linetype polyline
'left to right direction
hide fields


namespace Agregado_Formulario #BAAAAA {
entity Formulario{
    - FormularioNome FormularioNome
    - FormularioId FormularioId
    --
 }

class Campo{}

class ScriptValidacao{}

.Formulario "1" --> "1..*" Campo : tem
Campo "1" --> "0..1" ScriptValidacao : tem

}
namespace Agregado_Servico #DDDDDD{
entity Servico{
    - ServicoId ServicoId
    - PalavraChave PalavraChave
    --
}
'.Servico "1" --> "0..1" Aprovacao
.Servico "1" -- "1..*" .CatalogoServico : > Organizados em
}

namespace Agregado_TarefaSpec #DEEEEE{
entity TarefaSpec{}

entity TarefaSpecManual{}

entity TarefaSpecAutomatica{}

class TarefaSpecId<<Value Object>>{}

class ScriptTarefaSpec{}

class TipoTarefaSpec<<Value Object>> {}

.TarefaSpecAutomatica "1" --> "1" ScriptTarefaSpec : contém >

.Pedido "1" --- "1" .TarefaSpec
.TarefaSpec "1" --> "1" TipoTarefaSpec
.TarefaSpec "1" -> "1" TarefaSpecId
.TarefaSpec "1" <|-- "1" .TarefaSpecAutomatica : é
.TarefaSpec "1" <|-- "1" .TarefaSpecManual : é
}

namespace Agregado_Equipa #DAAAAA{

entity Equipa {
    -EquipaId EquipaId
    -Descricao Descricao
    --
}

}

namespace Agregado_Pedido #BADDDD{
entity Pedido{
    - Urgencia Urgencia
    - Estado Estado
    - DataLimiteResolucao DataLimiteResolucao
    - FicheiroAnexado FicheiroAnexado
    - PedidoId PedidoId
    - Prioridade Prioridade
    - Feedback Feedback
    --
}

entity FormularioPreenchido{}


}

namespace Agregado_Colaborador #DEEFFA {
entity Colaborador{
    - NomeCompleto NomeCompleto
    - NomeAbreviado NomeAbreviado
    - Morada Morada
    - Data Data
    - NumeroMecanografico NumeroMecanografico
    - Contacto Contacto
    - Funcao Funcao
    - CodigoEquipa CodigoEquipa
    --
}

}

namespace Agregado_CatalogoServico #AABBDD{

entity CatalogoServico{
    - CatalogoServicoId CatalogoServicoId
    - Titulo Titulo
    - DescricaoBreve DescricaoBreve
    - DescricaoCompleta DescricaoCompleta
    - Icone Icone
    --
}
class CriterioAcesso<<Value Object>>{}

.CatalogoServico "1" --> "1..*" "CriterioAcesso"
CriterioAcesso "1..*" --> .Equipa

}

namespace Agregado_TipoEquipa #BAADDC{
entity TipoEquipa{
    -TipoEquipaId TipoEquipaId
    -Cor cor
    -Descricao Descricao
    --
}
}

namespace Agregado_NivelCriticidade #CCCAAA{
entity NivelCriticidade{
    -NivelCriticidadeId id
    -int valor
    -Cor cor
    --
}

class Objetivo <<Value Object>> {
    -int tempoResolucaoMedio
    -int tempoAprovacaoMedio
    -int tempoResolucaoMax
    -int tempoAprovacaoMax
    --
}

.NivelCriticidade "1" --> "1..*" Objetivo

}

namespace Agregado_Tarefa #ABCDAA{
entity Tarefa{
    -TarefaId id
    -Data data
    -Descricao descricao
    -Colaborador assignatario
    --
}
class Aprovacao <<Value Object>> {}


entity TarefaManual{}

entity TarefaAutomatico{}


.Pedido "1" --- "1" .Tarefa
.Tarefa "1" --> "0..1" Aprovacao
.TarefaManual "1" --> "1" .Formulario : contém >
.Tarefa "1" <|-- "1" .TarefaAutomatico : é
.Tarefa "1" <|-- "1" .TarefaManual : é
}



.Equipa "1" --> "1" .TipoEquipa : pertence >
.Servico "1" --> "1" TarefaSpec : realiza
.Servico "1" --> "1" TarefaSpec : aprova
.Equipa "1" --> "1..*" Colaborador : É constituida por >
.TarefaSpecManual "1" --> "1" .Formulario : contém >
Organizacao "1" ..> "*" .Servico : disponibiliza >
Organizacao "1" ..> "1..*" .Equipa : define >
Organizacao "1" ..> "1..*" .TipoEquipa : define >

.CatalogoServico "1..*" --> "1" NivelCriticidade : Especifica >
.CatalogoServico "*" <-- "1" .CatalogoServico : contém
.Servico "1" -- "1" Formulario : especifica >
.Servico "*" <-- "1" .CatalogoServico : contém
.Servico "*" --> "1" .NivelCriticidade : < qualifica
.Pedido "1" --> "1" .FormularioPreenchido
.Pedido "*" --> "1" .Servico : Refere >
'.Pedido "1" --> "1" .Formulario : utiliza >

.Colaborador "1" --> "1" .Colaborador : é responsável
.Colaborador "1" <-- "*" .Pedido : responde >
.Colaborador "1" ..> "*" .Servico : executa
.Colaborador "1" ..> "*" .TarefaSpec : executa
.Colaborador "1" ..> "*" .TarefaSpec : aprova

.Servico "*" --> "1" .NivelCriticidade : > Pode alterar
.Servico "*" --> "1..*" Agregado_NivelCriticidade.Objetivo : > Pode alterar

'.FormularioPreenchido "1" --|> "1" Formulario : é

.Tarefa  "1" ---- "1" .TarefaSpec : é >
class Organizacao{}


@enduml