
/* Este modelo de domínio deve respeitar DDD */
@startuml
skinparam linetype polyline
'left to right direction
hide fields

namespace Agregado_Servico #DDDDDD{
entity Servico{
    - ServicoId ServicoId
    - PalavraChave PalavraChave
    --
}

class ScriptValidacao{}

entity Formulario{
    - int idServico
    - FormularioNome FormularioNome
    - FormularioId FormularioId
    --
 }

class Campo{}
.Formulario "1" --> "1..*" Campo : tem


Campo "1" --> "0..1" ScriptValidacao : tem
.Servico "1" -- "1..*" .CatalogoServico : > Organizados em
.Servico "1" -- "1" .Formulario
}

namespace Agregado_Tarefa #DEEEEE{
entity Tarefa{}

entity TarefaManual{}

entity TarefaAutomatica{}


entity TarefaAprovacao{}

entity TarefaRealizacao{}

class TarefaId<<Value Object>>{}

class ScriptTarefa{}

.TarefaAutomatica --|> .TarefaRealizacao : é
.TarefaManual -|> .TarefaRealizacao : é
.TarefaAutomatica "1" --> "1" ScriptTarefa : contém >

.Pedido "1" --- "1" .Tarefa

.Tarefa "1" -> "1" TarefaId
.Tarefa "1" <|-- "1" .TarefaAprovacao : é
.Tarefa "1" <|-- "1" .TarefaRealizacao : é
}

namespace Agregado_Equipa #DAAAAA{

entity Equipa {
    -EquipaId EquipaId
    -Descricao Descricao
    --
}

}

namespace Agregado_Pedido #BADDDD{
entity Pedido{
    - Urgencia Urgencia
    - Estado Estado
    - DataLimiteResolucao DataLimiteResolucao
    - FicheiroAnexado FicheiroAnexado
    - PedidoId PedidoId
    - Prioridade Prioridade
    - Feedback Feedback
    --
}

entity FormularioPreenchido{}


}

namespace Agregado_Colaborador #DEEFFA {
entity Colaborador{
    - NomeCompleto NomeCompleto
    - NomeAbreviado NomeAbreviado
    - Morada Morada
    - Data Data
    - NumeroMecanografico NumeroMecanografico
    - Contacto Contacto
    - Funcao Funcao
    - CodigoEquipa CodigoEquipa
    --
}

}

namespace Agregado_CatalogoServico #AABBDD{

entity CatalogoServico{
    - CatalogoServicoId CatalogoServicoId
    - Titulo Titulo
    - DescricaoBreve DescricaoBreve
    - DescricaoCompleta DescricaoCompleta
    - Icone Icone
    --
}
entity CriterioAcesso{}

}

namespace Agregado_TipoEquipa #BAADDC{
entity TipoEquipa{
    -TipoEquipaId TipoEquipaId
    -Cor cor
    -Descricao Descricao
    --
}
}

namespace Agregado_NivelCriticidade #CCCAAA{
entity NivelCriticidade{}
class NivelCriticidadeId <<Value Object>>{}
class Objetivo <<Value Object>>{}
class Etiqueta <<Value Object>>{}
class Valor <<Value Object>>{}
class Designacao <<Value Object>>{}
class Cor<<Value Object>>{}

.NivelCriticidade "1" --> "1" NivelCriticidadeId
.NivelCriticidade "1" --> "1..*" Objetivo
.NivelCriticidade "1" --> "1" Etiqueta
.NivelCriticidade "1" --> "1" Valor
.NivelCriticidade "1" --> "1" Designacao
.NivelCriticidade "1" --> "1" Cor
}



.Equipa "1" --> "1" .TipoEquipa : pertence >
.Equipa "*" -- "0..1" .CriterioAcesso
.CriterioAcesso "*" -- "1" .CatalogoServico

.Pedido "1" -- "1" .TarefaAprovacao


.TarefaManual "1" -- "1" .Formulario
Organizacao "1" ..> "*" .Servico : disponibiliza >
Organizacao "1" ..> "1..*" .Equipa : define >
Organizacao "1" ..> "1..*" .TipoEquipa : define >

.CatalogoServico "*" <-- "1" .CatalogoServico : contém
.Servico "*" <-- "1" .CatalogoServico : contém
.Servico "*" --> "1" .NivelCriticidade : pode ter >
.Pedido "1" -- "1" .FormularioPreenchido
.Pedido "*" --> "1" .Servico : Refere >

.Colaborador "1" --> "1" .Colaborador : é responsável
.Colaborador "1" <-- "*" .Pedido : responde
.Colaborador "1" ..> "*" .Servico : solicita
.Colaborador "1" ..> "*" .Tarefa : executa e delega
.Colaborador "1" ..> "*" .TarefaAprovacao : aprova

.FormularioPreenchido "1" --|> "1" Formulario : é


class Organizacao{}


@enduml