
/* Este modelo de domínio deve respeitar DDD */
@startuml
skinparam linetype polyline
'left to right direction


namespace Agregado_Servico #DDDDDD{
entity Servico{
}
class ServicoId <<Value Object>>{}
class PalavraChave <<Value Object>>{}

.Servico "1" --> "1" ServicoId
.Servico "1" --> "1..*" PalavraChave


entity Formulario{
 int idServico
 }

class FormularioNome <<Value Object>>{}

class FormularioId <<Value Object>>{}

class FormularioTipo <<Value Object>>{}

.Formulario "1" --> "1" FormularioNome
.Formulario "1" --> "1" FormularioId
.Formulario "1" --> "1" FormularioTipo
.Servico "1" -- "1..*" .CatalogoServico : > Organizados em
.Servico "1" -- "1" .Formulario
}

namespace Agregado_Tarefa #DEEEEE{
entity Tarefa{}

entity TarefaManual{}

entity TarefaAutomatica{}

entity Script{}

entity AtividadeAprovacao{}

entity TarefaAprovacao{}

entity TarefaRealizacao{}

.AtividadeAprovacao "1" -- "1" .Tarefa
.TarefaAutomatica "1" --> "1" .Script : contém >

.TarefaAutomatica -|> .Tarefa : é
.TarefaManual --|> .Tarefa : é

.Pedido "1" --- "1" .Tarefa

.Tarefa "1" --> "1" TipoTarefa
.Tarefa "1" -> "1" TarefaId
.Tarefa "1" <|-- "1" .TarefaAprovacao : é
.Tarefa "1" <|-- "1" .TarefaRealizacao : é
}



namespace Agregado_Pedido #BADDDD{
entity Pedido{}

class Urgencia <<Value Object>>{}
class Estado <<Value Object>>{}
class DataLimiteResolucao <<Value Object>>{}
class FicheiroAnexado <<Value Object>>{}
class PedidoId <<Value Object>>{}
class Prioridade <<Value Object>>{}
class Feedback <<Value Object>>{}

.Pedido "1" -> "1" Urgencia
.Pedido "1" -> "1" Estado
.Pedido "1" -> "1" DataLimiteResolucao
.Pedido "1" -> "0..*" FicheiroAnexado
.Pedido "1" -> "1" PedidoId
.Pedido "1" -> "1" Prioridade
.Pedido "1" -> "1" Feedback

}


namespace Agregado_CatalogoServico #AABBDD{

entity CatalogoServico{
}

class CatalogoServicoId <<Value Object>>{}
class Titulo <<Value Object>>{}
class DescricaoBreve <<Value Object>>{}
class DescricaoCompleta <<Value Object>>{}
class Icone <<Value Object>>{}

.CatalogoServico "1" --> "1" CatalogoServicoId
.CatalogoServico "1" --> "1" Titulo
.CatalogoServico "1" --> "1" DescricaoBreve
.CatalogoServico "1" --> "1" DescricaoCompleta
.CatalogoServico "1" --> "1" Icone

}




namespace Agregado_NivelCriticidade #CCCAAA{
entity NivelCriticidade{}
class NivelCriticidadeId <<Value Object>>{}
class Objetivo <<Value Object>>{}
class Etiqueta <<Value Object>>{}
class Valor <<Value Object>>{}
class Designacao <<Value Object>>{}
class CorCriticidade <<Value Object>>{}

.NivelCriticidade "1" --> "1" NivelCriticidadeId
.NivelCriticidade "1" --> "1..*" Objetivo
.NivelCriticidade "1" --> "1" Etiqueta
.NivelCriticidade "1" --> "1" Valor
.NivelCriticidade "1" --> "1" Designacao
.NivelCriticidade "1" --> "1" CorCriticidade
}

entity CriterioAcesso{}



.CriterioAcesso "*" -- "1" .CatalogoServico

.Pedido "1" -- "1" .AtividadeAprovacao

.TarefaManual "1" -- "1" .Formulario

.CatalogoServico "*" <-- "1" .CatalogoServico : contém
.Servico "*" <-- "1" .CatalogoServico : contém

.Servico "*" --> "1" .NivelCriticidade : pode ter >
.Pedido "1" -- "1" .Formulario
.Pedido "*" --> "1" .Servico : Refere >

Agregado_NivelCriticidade.CorCriticidade --|> Cor : é

class Cor<<Value Object>>{}

@enduml